version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: usuario
      MONGO_INITDB_ROOT_PASSWORD: contraseña
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data:
